{% set python_min = "3.10" %}
{% set version = "1.9.1" %}

package:
  name: xcube
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube/archive/v{{ version }}.tar.gz
  sha256: d3c7a7a1a0314fa0db2fcf7322500f567267d6a8814602b880786f4772199271

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xcube = xcube.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
  # Required
    - affine >=2.2
    - altair
    - botocore >=1.34.51
    - cftime >=1.6.3
    - chartlets >=0.1.0
    - click >=8.0
    - cmocean >=2.0
    - dask >=2021.6
    - dask-image >=0.6
    - deprecated >=1.2
    - distributed >=2021.6
    - fiona >=1.8
    - fsspec >=2021.6
    - gdal >=3.0
    - geopandas >=0.8
    - jdcal >=1.4
    - jsonschema >=3.2
    - kerchunk
    - mashumaro
    - matplotlib-base >=3.8.3
    - netcdf4 >=1.5
    - numba >=0.52
    - numcodecs >=0.12.1
    - numpy >=1.16
    - pandas >=1.3
    - pillow >=6.0
    - pip
    - pyjwt >=1.7
    - pyproj >=3.0
    - pyyaml >=5.4
    - rasterio >=1.2
    - requests >=2.25
    - rfc3339-validator >=0.1
    - rioxarray >=0.11
    - s3fs >=2021.6
    - setuptools >=41.0
    - shapely >=1.6
    - tabulate >=0.9
    - tornado >=6.0
    - urllib3 >=2.0
    - xarray >=2024.7
    - zarr >=2.11,<3
test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube
    - xcube.cli.main
  commands:
    - xcube --help

about:
  summary: xcube is a Python package for generating and exploiting data cubes powered by xarray, dask, and zarr
  home: https://github.com/xcube-dev/xcube
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube is a Python package for generating and exploiting data cubes powered by xarray, dask, and zarr. It has been designed in the context of Earth Observation data.
  doc_url: https://xcube.readthedocs.io
  dev_url: https://github.com/xcube-dev/xcube

extra:
  recipe-maintainers:
    - konstntokas
    - AliceBalfanz
    - TejasMorbagal
    - forman
    - pont-us
    - thomasstorm
    - TonioF
    - ruchimotwaniBC
    - b-yogesh
